# Generated by Django 3.1.5 on 2021-01-26 10:13

from django.db import migrations
import e_ductus.fields


class Migration(migrations.Migration):

    dependencies = [
        ('e_ductus', '0004_file_image_text_video'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='content',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='content',
            name='order',
            field=e_ductus.fields.OrderField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='module',
            name='order',
            field=e_ductus.fields.OrderField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
