# Generated by Django 3.1.5 on 2021-02-23 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_ductus', '0007_course_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='file',
            field=models.FileField(blank=True, upload_to='images'),
        ),
    ]
